FROM node:20-alpine

# This file makes sure Nuxt is run in the container and is in the same Docker network as Directus. 
# Otherwhise Nuxt would be run completely locally.
# The .dev suffix is a convention for the dev environment.

WORKDIR /app

# Copy package files (for npm install) - this is done before copying the rest to leverage Docker caching
COPY package*.json ./

# Install dependencies - this will be cached by Docker, so it won't run again unless package.json changes
RUN npm install

# Copy the rest of the application code (this will be mounted via volume in development)
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]